# Generated by Django 5.0.3 on 2024-07-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_user_recipe_calories_recipe_carbs_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
    ]
